# Generated by Django 5.2 on 2025-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PRO", "Pro"), ("WHALE", "Whale")],
                default="FREE",
                max_length=10,
            ),
        ),
    ]
